version: '3.8'

services:
  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5430:5432"
  server:
    build: .
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
