"""Add limit rides to user

Revision ID: 7abbb1e074f9
Revises: 28fa591bfbd6
Create Date: 2023-09-20 04:07:06.814818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abbb1e074f9'
down_revision = '28fa591bfbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_bluetooth_device_id'), 'bluetooth_device', ['id'])
    op.create_unique_constraint(op.f('uq_payment_status_id'), 'payment_status', ['id'])
    op.create_unique_constraint(op.f('uq_preference_account_id'), 'preference_account', ['id'])
    op.create_unique_constraint(op.f('uq_ride_id'), 'ride', ['id'])
    op.create_unique_constraint(op.f('uq_ride_payment_id'), 'ride_payment', ['id'])
    op.create_unique_constraint(op.f('uq_ride_status_id'), 'ride_status', ['id'])
    op.create_unique_constraint(op.f('uq_sbp_account_id'), 'sbp_account', ['id'])
    op.create_unique_constraint(op.f('uq_touches_id'), 'touches', ['id'])
    op.create_unique_constraint(op.f('uq_transport_id'), 'transport', ['id'])
    op.create_unique_constraint(op.f('uq_transport_type_id'), 'transport_type', ['id'])
    op.add_column('user', sa.Column('limit_rides', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_user_id'), 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_id'), 'user', type_='unique')
    op.drop_column('user', 'limit_rides')
    op.drop_constraint(op.f('uq_transport_type_id'), 'transport_type', type_='unique')
    op.drop_constraint(op.f('uq_transport_id'), 'transport', type_='unique')
    op.drop_constraint(op.f('uq_touches_id'), 'touches', type_='unique')
    op.drop_constraint(op.f('uq_sbp_account_id'), 'sbp_account', type_='unique')
    op.drop_constraint(op.f('uq_ride_status_id'), 'ride_status', type_='unique')
    op.drop_constraint(op.f('uq_ride_payment_id'), 'ride_payment', type_='unique')
    op.drop_constraint(op.f('uq_ride_id'), 'ride', type_='unique')
    op.drop_constraint(op.f('uq_preference_account_id'), 'preference_account', type_='unique')
    op.drop_constraint(op.f('uq_payment_status_id'), 'payment_status', type_='unique')
    op.drop_constraint(op.f('uq_bluetooth_device_id'), 'bluetooth_device', type_='unique')
    # ### end Alembic commands ###