"""Refactor touche

Revision ID: c705ad3645f6
Revises: f50ff84b65c3
Create Date: 2023-10-13 21:58:37.912202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c705ad3645f6'
down_revision = 'f50ff84b65c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    op.add_column('touches', sa.Column('uuid', sa.String(), nullable=False))
    op.create_unique_constraint(op.f('uq_touches_id'), 'touches', ['id'])
    op.drop_constraint('fk_touches_ride_id_ride', 'touches', type_='foreignkey')
    op.drop_constraint('fk_touches_user_id_user', 'touches', type_='foreignkey')
    op.drop_column('touches', 'ride_id')
    op.drop_column('touches', 'user_id')
    op.create_table('uuid_device',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('uuid', sa.String(), nullable=False),
                    sa.Column('token', sa.String(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_uuid_device_user_id_user'),
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_uuid_device')),
                    sa.UniqueConstraint('id', name=op.f('uq_uuid_device_id'))
                    )
    op.create_index(op.f('ix_uuid_device_token'), 'uuid_device', ['token'], unique=True)
    op.create_index(op.f('ix_uuid_device_uuid'), 'uuid_device', ['uuid'], unique=True)

    op.execute('''INSERT INTO uuid_device(id,token,uuid, user_id) VALUES (1, 'co8Kp5PNR_uBLOShRgndZn:APA91bEPcavU3wdsg3ZJaXy6MZqALYAJUuIffXq85kj719tvNCO6UNDVp5Ezw2-l0Kk-jRlBO7U1ZBZ3kFdk14vMIJ-7vDMGWdW2c2apncF61kELYXihYHcr2211PVpxPwQUZIZkKvs7', 'e32cb627-ea88-49d6-8854-0429206e125f', 1);''')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('touches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('touches', sa.Column('ride_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_touches_user_id_user', 'touches', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_touches_ride_id_ride', 'touches', 'ride', ['ride_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_touches_id'), 'touches', type_='unique')
    op.drop_column('touches', 'uuid')
    op.drop_index(op.f('ix_uuid_device_uuid'), table_name='uuid_device')
    op.drop_index(op.f('ix_uuid_device_token'), table_name='uuid_device')
    op.drop_table('uuid_device')
    # ### end Alembic commands ###